### ISSUE TITLE
`multithreading` branch idles forever

### ISSUE THREAD

**Issue by ifndefJOSH** [fluentverification/stamina-storm#24]
I'm not sure why but no threads are explored, but all idle forever.

**Comment by ifndefJOSH** [comment]
According to GDB, there is an issue with the main exploration queue in the exploration threads. At around line 144 of `IterativeExplorationThread.cpp` there is something wrong. Here is an example backtrace:

```
#1  0x00007ffff4e6d6cb in std::deque<std::pair<stamina::builder::ProbabilityState<unsigned int>*, storm::storage::BitVector&>, std::allocator<std::pair<stamina::builder::ProbabilityState<unsigned int>*, storm::storage::BitVector&> > >::empty (this=0x650c88) at /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/stl_deque.h:1309
#2  0x00007ffff4e6d3d6 in stamina::builder::threads::IterativeExplorationThread<double, storm::models::sparse::StandardRewardModel<double>, unsigned int>::exploreStates (this=0x650bd0) at /home/josh/Documents/work/dev/stamina-storm/src/stamina/builder/threads/IterativeExplorationThread.cpp:144
...some more irrelevant stack frames
```

**Comment by ifndefJOSH** [comment]
No longer idles forever but doesn't explore beyond the 14 states the starter thread explores
